# Generated by Django 6.0 on 2025-12-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
